"use client";

import { Check, Copy, Download, Layers, Loader2, Sparkles } from "lucide-react";
import { useRouter } from "next/navigation";
import { useState } from "react";

import { ReflectionSection } from "@/components/reflection-sections";
import { Button } from "@/components/ui/button";
import type { ChildReflection } from "@/lib/types";
import {
  panelHighlightClass,
  sectionLabelClass,
  staggerSectionsClass,
} from "@/lib/ui-classes";

export function ChildReflectionCompanion({
  childId,
  childName,
  childAge,
  childClass,
  observationCount,
  initialReflection,
}: {
  childId: string;
  childName: string;
  childAge?: number | null;
  childClass?: string | null;
  observationCount: number;
  initialReflection: ChildReflection | null;
}) {
  const router = useRouter();
  const [reflection, setReflection] = useState(initialReflection);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [copied, setCopied] = useState(false);

  const isStale =
    reflection != null && reflection.observation_count < observationCount;

  async function generate() {
    setLoading(true);
    setError(null);
    try {
      const res = await fetch("/api/reflect/child", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ childId }),
      });
      const data = (await res.json()) as ChildReflection & { error?: string };
      if (!res.ok) {
        setError(data.error ?? "Could not generate reflection.");
        return;
      }
      setReflection({
        id: data.id,
        child_id: childId,
        patterns: data.patterns,
        questions: data.questions,
        connections: data.connections,
        observation_count: data.observation_count,
        created_at: data.created_at,
      });
      router.refresh();
    } catch {
      setError("Could not reach the server.");
    } finally {
      setLoading(false);
    }
  }

  function buildPlainText(r: ChildReflection) {
    const meta = [
      childAge != null ? `Age ${childAge}` : null,
      childClass ?? null,
    ]
      .filter(Boolean)
      .join(" · ");

    const date = new Date(r.created_at).toLocaleDateString("en", {
      dateStyle: "long",
    });

    const lines: string[] = [
      `Documentation Reflection — ${childName}`,
      meta ? meta : "",
      `Based on ${r.observation_count} ${r.observation_count === 1 ? "entry" : "entries"} · ${date}`,
      ``,
      `PATTERNS NOTICED`,
      `────────────────`,
      ...r.patterns.map((p) => `• ${p}`),
      ``,
      `REFLECTION QUESTIONS`,
      `────────────────────`,
      ...r.questions.map((q) => `• ${q}`),
      ``,
      `CONNECTIONS WORTH EXPLORING`,
      `───────────────────────────`,
      ...r.connections.map((c) => `• ${c}`),
      ``,
      `Generated by Spark by Sher — Documentation Reflection Companion`,
    ];
    return lines.filter((l, i) => !(i === 1 && !meta)).join("\n");
  }

  async function handleCopy() {
    if (!reflection) return;
    await navigator.clipboard.writeText(buildPlainText(reflection));
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  }

  function handlePrint() {
    window.print();
  }

  if (observationCount === 0) return null;

  return (
    <section className={panelHighlightClass}>
      {/* Header */}
      <div className="space-y-1.5">
        <h2 className={`${sectionLabelClass} flex items-center gap-2`}>
          <Layers className="size-3" />
          Reflection across documentation
        </h2>
        <p className="text-[13px] leading-[1.6] text-[#6b7a76]">
          Revisit all of {childName}&apos;s observations together — patterns and
          questions across all {observationCount}{" "}
          {observationCount === 1 ? "entry" : "entries"}.
        </p>
      </div>

      {/* Stale warning */}
      {isStale && (
        <p className="spark-claim-banner mt-3 text-[13px]">
          New observations have been added. Regenerate to include the full set.
        </p>
      )}

      {/* Generate CTA */}
      {!reflection && (
        <div className="mt-4">
          <Button
            type="button"
            variant="cta"
            size="lg"
            disabled={loading}
            onClick={() => void generate()}
            className="w-full sm:w-auto"
          >
            {loading ? (
              <>
                <Loader2 className="animate-spin" />
                Generating…
              </>
            ) : (
              <>
                <Sparkles className="spark-icon-pulse" />
                Reflect across all observations
              </>
            )}
          </Button>
        </div>
      )}

      {/* Error */}
      {error && (
        <p
          role="alert"
          className="mt-3 rounded-lg border border-destructive/30 bg-destructive/10 px-3 py-2.5 text-[13px] text-destructive"
        >
          {error}
        </p>
      )}

      {/* Reflection output */}
      {reflection && (
        <div className={`${staggerSectionsClass} mt-4 flex flex-col gap-3`}>
          <p className="text-[11px] text-[#8a9490]">
            Based on {reflection.observation_count}{" "}
            {reflection.observation_count === 1 ? "entry" : "entries"} ·{" "}
            {new Date(reflection.created_at).toLocaleString("en", {
              dateStyle: "medium",
              timeStyle: "short",
            })}
          </p>
          <ReflectionSection
            title="Patterns noticed"
            intro="Across the full body of documentation — not one moment in isolation."
            items={reflection.patterns}
            variant="patterns"
          />
          <ReflectionSection
            title="Reflection questions"
            intro="Questions that may connect multiple entries. You may wish to consider…"
            items={reflection.questions}
            variant="questions"
          />
          <ReflectionSection
            title="Connections worth exploring"
            intro="How documentation over time might relate — offered with curiosity."
            items={reflection.connections}
            variant="connections"
          />

          {/* ── Toolbar: export + regenerate ── */}
          <div className="flex items-center justify-between gap-3 border-t border-[rgba(154,124,46,0.15)] pt-3 print:hidden">
            <div className="flex items-center gap-1.5">
              {/* Copy */}
              <button
                type="button"
                onClick={() => void handleCopy()}
                title="Copy to clipboard"
                className="flex h-8 w-8 items-center justify-center rounded-lg border border-[rgba(154,124,46,0.2)] bg-white text-[#9a7c2e] transition-colors hover:bg-[#faf4e6]"
              >
                {copied ? <Check className="size-3.5" /> : <Copy className="size-3.5" />}
              </button>
              {/* PDF */}
              <button
                type="button"
                onClick={handlePrint}
                title="Download PDF"
                className="flex h-8 w-8 items-center justify-center rounded-lg border border-[rgba(154,124,46,0.2)] bg-white text-[#9a7c2e] transition-colors hover:bg-[#faf4e6]"
              >
                <Download className="size-3.5" />
              </button>
            </div>
            {/* Regenerate — right-aligned, clearly secondary */}
            <button
              type="button"
              disabled={loading}
              onClick={() => void generate()}
              className="text-[11px] text-[#c8a85a] underline underline-offset-2 transition-colors hover:text-[#9a7c2e] disabled:opacity-40"
            >
              {loading
                ? "Regenerating…"
                : `Regenerate observations for ${childName}`}
            </button>
          </div>
        </div>
      )}
    </section>
  );
}