"use client";

import { Check, Copy, Download, Loader2, Share2, Sparkles } from "lucide-react";
import { useRouter } from "next/navigation";
import { useState } from "react";

import { createShareToken } from "@/app/actions/share";
import { ReflectionSection } from "@/components/reflection-sections";
import { Button } from "@/components/ui/button";
import type { Reflection } from "@/lib/types";
import { exportButtonClass, pullQuoteClass, staggerSectionsClass } from "@/lib/ui-classes";

export function ReflectionCompanion({
  observationId,
  initialReflection,
  observationText,
  childName,
  observedAt,
}: {
  observationId: string;
  initialReflection: Reflection | null;
  observationText: string;
  childName: string;
  observedAt: string;
}) {
  const router = useRouter();
  const [reflection, setReflection] = useState(initialReflection);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [copied, setCopied] = useState(false);
  const [shareUrl, setShareUrl] = useState<string | null>(null);
  const [shareLoading, setShareLoading] = useState(false);
  const [shareCopied, setShareCopied] = useState(false);
  const [shareError, setShareError] = useState<string | null>(null);

  async function generate() {
    setLoading(true);
    setError(null);
    try {
      const res = await fetch("/api/reflect", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ observationId }),
      });
      const data = (await res.json()) as Reflection & { error?: string };
      if (!res.ok) {
        setError(data.error ?? "Could not generate reflection.");
        return;
      }
      setReflection({
        id: data.id,
        observation_id: observationId,
        patterns: data.patterns,
        questions: data.questions,
        connections: data.connections,
        created_at: data.created_at,
      });
      router.refresh();
    } catch {
      setError("Could not reach the server.");
    } finally {
      setLoading(false);
    }
  }

  function buildPlainText(r: Reflection) {
    const date = new Date(observedAt).toLocaleDateString("en", {
      dateStyle: "long",
    });
    const lines: string[] = [
      `Documentation Reflection — ${childName}`,
      `${date}`,
      ``,
      `OBSERVATION`,
      `───────────`,
      observationText,
      ``,
      `PATTERNS NOTICED`,
      `────────────────`,
      ...r.patterns.map((p) => `• ${p}`),
      ``,
      `REFLECTION QUESTIONS`,
      `────────────────────`,
      ...r.questions.map((q) => `• ${q}`),
      ``,
      `CONNECTIONS WORTH EXPLORING`,
      `───────────────────────────`,
      ...r.connections.map((c) => `• ${c}`),
      ``,
      `Generated by Spark by Sher — Documentation Reflection Companion`,
    ];
    return lines.join("\n");
  }

  async function handleCopy() {
    if (!reflection) return;
    await navigator.clipboard.writeText(buildPlainText(reflection));
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  }

  function handlePrint() {
    window.print();
  }

  async function handleShare() {
    setShareLoading(true);
    setShareError(null);

    const result = await createShareToken(observationId);

    setShareLoading(false);

    if ("error" in result) {
      setShareError(result.error);
      return;
    }

    setShareUrl(result.url);
    await navigator.clipboard.writeText(result.url);
    setShareCopied(true);
    setTimeout(() => setShareCopied(false), 2000);
  }

  async function handleCopyShareUrl() {
    if (!shareUrl) return;
    await navigator.clipboard.writeText(shareUrl);
    setShareCopied(true);
    setTimeout(() => setShareCopied(false), 2000);
  }

  return (
    <div className="flex flex-col gap-6">
      <p className={pullQuoteClass}>
        The educator remains the thinker. This companion offers patterns,
        questions, and connections to revisit—you interpret what they mean for
        each child.
      </p>

      {!reflection && (
        <Button
          type="button"
          variant="cta"
          size="lg"
          disabled={loading}
          onClick={() => void generate()}
          className="w-full sm:w-auto"
        >
          {loading ? (
            <>
              <Loader2 className="animate-spin" />
              Generating…
            </>
          ) : (
            <>
              <Sparkles className="spark-icon-pulse" />
              Generate reflection
            </>
          )}
        </Button>
      )}

      {error && (
        <p
          role="alert"
          className="rounded-lg border border-destructive/30 bg-destructive/10 px-4 py-3 text-sm text-destructive"
        >
          {error}
        </p>
      )}

      {reflection && (
        <div className={`${staggerSectionsClass} flex flex-col gap-6`}>
          <ReflectionSection
            title="Patterns noticed"
            intro="Language and ideas present in the documentation—not conclusions about the child's thinking."
            items={reflection.patterns}
            variant="patterns"
          />
          <ReflectionSection
            title="Reflection questions"
            intro="Questions for you to sit with. You may wish to consider…"
            items={reflection.questions}
            variant="questions"
          />
          <ReflectionSection
            title="Connections worth exploring"
            intro="Possible directions to revisit—offered with curiosity, not certainty."
            items={reflection.connections}
            variant="connections"
          />

          {/* ── Export actions ── */}
          <div className="flex flex-wrap items-center gap-2 border-t border-[rgba(154,124,46,0.1)] pt-4">
            <button
              type="button"
              onClick={() => void handleCopy()}
              className={`${exportButtonClass} print:hidden`}
            >
              {copied ? (
                <>
                  <Check className="size-3.5" />
                  Copied
                </>
              ) : (
                <>
                  <Copy className="size-3.5" />
                  Copy to clipboard
                </>
              )}
            </button>
            <button
              type="button"
              onClick={handlePrint}
              className={`${exportButtonClass} print:hidden`}
            >
              <Download className="size-3.5" />
              Download PDF
            </button>
            <button
              type="button"
              disabled={shareLoading}
              onClick={() => void handleShare()}
              className={`${exportButtonClass} print:hidden`}
            >
              {shareLoading ? (
                <Loader2 className="size-3.5 animate-spin" />
              ) : shareCopied ? (
                <Check className="size-3.5" />
              ) : (
                <Share2 className="size-3.5" />
              )}
              {shareCopied ? "Copied" : "Share"}
            </button>
            {shareUrl && (
              <div className="flex w-full flex-wrap items-center gap-2 print:hidden">
                <input
                  type="text"
                  readOnly
                  value={shareUrl}
                  aria-label="Share link"
                  className="min-w-0 flex-1 rounded-lg border border-[rgba(154,124,46,0.2)] bg-white px-3 py-1.5 text-[12px] text-[#3d4f4c]"
                />
                <button
                  type="button"
                  onClick={() => void handleCopyShareUrl()}
                  className={exportButtonClass}
                >
                  {shareCopied ? (
                    <>
                      <Check className="size-3.5" />
                      Copied
                    </>
                  ) : (
                    <>
                      <Copy className="size-3.5" />
                      Copy link
                    </>
                  )}
                </button>
              </div>
            )}
            {shareError && (
              <p role="alert" className="text-[12px] text-destructive print:hidden">
                {shareError}
              </p>
            )}
            <Button
              type="button"
              variant="outline"
              disabled={loading}
              onClick={() => void generate()}
              className="print:hidden"
            >
              {loading ? (
                <>
                  <Loader2 className="animate-spin" />
                  Regenerating…
                </>
              ) : (
                "Regenerate reflection"
              )}
            </Button>
          </div>

          {/* ── Print-only header (hidden on screen) ── */}
          <div className="print-only hidden">
            <p className="print-meta">
              {childName} · {new Date(observedAt).toLocaleDateString("en", { dateStyle: "long" })}
            </p>
            <p className="print-brand">Spark by Sher — Documentation Reflection Companion</p>
          </div>
        </div>
      )}
    </div>
  );
}